[package]
name = "device_support"
version = "0.1.0"
authors = ["Alexey Gerasev <alexey.gerasev@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]
log = "0.4"
simple_logger = "1.2.0"
lazy_static = "1.3.0"
epics = { git = "https://github.com/binp-automation/epics-rs", rev = "dc9885acefa48cffa3f1079b2556e551c9ba570d" }
#{ path = "../../epics-rs" }
ksfc-lxi = { git = "https://github.com/binp-automation/ksfc-lxi", rev = "eabeedf33d10e2adc116dce69ceb14eb566f86ff" }
#{ path = "../../ksfc-lxi" }
