[package]
name = "device_support"
version = "0.1.0"
authors = ["Alexey Gerasev <alexey.gerasev@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]
log = "0.4"
simple_logger = "1.2.0"
lazy_static = "1.3.0"
epics = { git = "https://github.com/binp-automation/epics-rs", rev = "f55e7096a59d6d9951ec4ca3a772e34085d48b59" }
#{ path = "../../epics-rs" }
ksfc-lxi = { git = "https://github.com/binp-automation/ksfc-lxi", rev = "eabeedf33d10e2adc116dce69ceb14eb566f86ff" }
#{ path = "../../ksfc-lxi" }
